version: '3.9'

services:
    mariadb-db:
        build: ./requirements/mariadb
        image: mariadb-db
        container_name: mariadb-db
        env_file: 
            - .env
        volumes:
            - db:/var/lib/mysql
        restart: on-failure
        networks:
            - my-inception
        expose:
            - 3306

    wordpress-wp:
        build: requirements/wordpress
        image: wordpress-wp
        depends_on:
            - mariadb-db
        container_name: wordpress-wp
        env_file: .env
        volumes:
            - wp:/var/www/html
        restart: on-failure
        networks:
            - my-inception
        expose:
            - 9000
        
    nginx-ngx:
        build: requirements/nginx
        image: nginx-server
        depends_on:
            - wordpress-wp
        container_name: nginx-ngx
        env_file: .env
        volumes:
            - wp:/var/www/html
        ports:
            - "443:443"
        restart: on-failure
        networks:
            - my-inception

networks:
    my-inception:
        driver: bridge

volumes:
    db:
        driver: local
        driver_opts:
            type: none
            device: /home/fialexan/data/mysql
            o: bind

    wp:
        driver: local
        driver_opts:
            type: none
            device: /home/fialexan/data/html
            o: bind
