CREATE DATABASE MARIADB_DATABASE;
CREATE USER 'MARIADB_USER'@'%' IDENTIFIED BY 'MARIADB_USER_PASS';
GRANT ALL PRIVILEGES ON MARIADB_DATABASE.* TO 'MARIADB_USER'@'%' IDENTIFIED BY 'MARIADB_USER_PASS';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MARIADB_ROOT_PASS';