CREATE USER IF NOT EXISTS '$MARIADB_USER_NAME'@'%' IDENTIFIED BY '$MARIADB_USER_PASS';
GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$MARIADB_USER_NAME'@'%' WITH GRANT OPTION;

UPDATE mysql.user SET password=passwprd('$MARIADB_ROOT_PASS') WHERE user='root';

FLUSH PRIVILEGES;
